name: Admin360-Reloaded
main: com.battleasya.admin360.Admin360
version: ${version}
api-version: 1.14
authors: [Dennie, Vidhu, Dartanboy, Technofied]
website: https://www.spigotmc.org/resources/28285/
description: Manage real-time help requests.
commands:
  ticket:
    description: Admin360 Command
    aliases: [request, helpop]
  admin360:
    description: Admin360 Command
permissions:
  admin360.*:
    description: Admin360 Commands
    children:
      admin360.staff.*:
        description: Admin360 Staff Commands
        default: op
        children:
          admin360.staff.basic: true
          admin360.staff.teleport: true
          admin360.staff.info: true
          admin360.staff.transfer: true
          admin360.staff.drop: true
          admin360.staff.purge: true
          admin360.staff.remove: true
          admin360.staff.hpstats: true
          admin360.staff.hptop: true
          admin360.staff.history: true
          admin360.staff.hpreset: true
          admin360.staff.fly: true
          admin360.staff.reload: true
      admin360.player.*:
        description: Admin360 Player Commands
        default: op
        children:
          admin360.player.basic: true
          admin360.player.status: true
          admin360.player.stats: true